Vagrant.configure(2) do |config|
  config.vm.define "web" do |web|
    web.vm.box = "apache-v0.4.3"
    web.ssh.insert_key = false
    web.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  end
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty32"
    db.ssh.insert_key = false
    db.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  end
end
